### ISSUE TITLE
b41T

### ISSUE THREAD

**Issue by Bassmeaux** [reaper7/M5Stack_BLE_client_Owon_B35T#1]
I have an owon b41T which seems to use mostly the same protocol to the b35t this was designed for. I was wondering where you got the info you needed to create this, as I would like to modify it for the b41t. The app compiles and runs and connects to my meter and I can control the meter ok with the m5stack but the numerical values from the meter are never displayed. Any ideas?
Thank you for all your great work :)

**Comment by reaper7** [comment]
numerical not work but icons?
info for reading:
https://hackaday.io/project/12922-bluetooth-data-owon-b35t-multimeter
info for reading and control:
https://github.com/akemnade/owon-tools
and of course some app for android phone (in my case) for experiments with reading and control
like BLE Scanner and nRF Connect
You can also uncomment lines 584-589 inside M5Stack_BLE_client_Owon_B35T.ino
and check on serial console what information from the meter is coming.
b35t reply bytes from 1-4 are value digits, You must check if b41t sending digits at this position
